singleQuote: true
trailingComma: es5
# prettier-plugin-sort-imports
importOrder: ['^react$', '<THIRD_PARTY_MODULES>', '^@/(.*)$', '^[./]']
importOrderSeparation: false
importOrderSortSpecifiers: true
