extends:
  - stylelint-config-standard
rules:
  function-name-case: null
  value-keyword-case: null
  selector-class-pattern: null
  color-function-notation: null
  alpha-value-notation: null
  at-rule-no-unknown: null
  selector-pseudo-class-no-unknown: null
  function-no-unknown: null
plugins:
  - stylelint-less
