default_language_version:
  node: system

repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [--settings-path, backend/.isort.cfg]
        exclude: '(migrations)'

  - repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
      - id: black
        exclude: '(migrations)'

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--config, backend/.flake8]
        exclude: '(migrations)'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          [
            'types-requests',
            'types-PyYAML',
            'types-pytz',
            'djangorestframework-stubs',
            'django-stubs',
            'djangorestframework',
            'django-filter',
            'drf-spectacular',
            'django-apscheduler',
            'django-cleanup',
            'jklib',
            'psycopg2-binary',
            'sentry-sdk',
            'dj_database_url',
          ]
        args: [--config, backend/mypy.ini]
        exclude: '(test_*)|(settings.py)|(manage.py)|(migrations)'

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        args:
          [
            --config,
            frontend/.stylelintrc.yml,
            --ignore-path,
            frontend/.stylelintignore,
            --fix,
          ]
        additional_dependencies:
          - stylelint@16.2.0
          - stylelint-config-css-modules@4.4.0
          - stylelint-config-idiomatic-order@10.0.0
          - stylelint-config-prettier@9.0.5
          - stylelint-config-standard@36.0.0
          - stylelint-prettier@5.0.0
          - postcss-less@6.0.0
        files: \.(css|less)$
        types: [file]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0'
    hooks:
      - id: prettier
        args:
          [
            --config,
            frontend/.prettierrc.yml,
            --ignore-path,
            frontend/.prettierignore,
          ]
        additional_dependencies:
          - prettier@3.2.4
          - '@trivago/prettier-plugin-sort-imports@4.3.0'
        exclude: '(html)|(md)|(txt)$'

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.56.0'
    hooks:
      - id: eslint
        args: [--config, frontend/.eslintrc.yml, --max-warnings=0]
        additional_dependencies:
          - eslint@8.56.0
          - eslint-config-airbnb@19.0.4
          - eslint-config-prettier@9.1.0
          - eslint-config-react-app@7.0.1
          - eslint-plugin-disable@2.0.3
          - eslint-plugin-flowtype@8.0.3
          - eslint-plugin-import@2.29.1
          - eslint-plugin-jsx-a11y@6.8.0
          - eslint-plugin-react@7.33.2
          - eslint-plugin-react-hooks@4.6.0
        files: \.(js|jsx|ts|tsx)$
        types: [file]
