version: '3'

services:
  api:
    image: django_react_starter_api
    container_name: django_react_starter_api
    build:
      context: ../
      dockerfile: ./Dockerfile
    env_file:
      - .env
    #    depends_on:
    #      - postgres
    networks:
      - django_react_starter_api
    ports:
      - '8000:8000'
    volumes:
      - .:/home/app/backend

#  postgres:
#    container_name: django_react_starter_postgres
#    image: postgres:15.2-alpine
#    env_file:
#      - .env
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    networks:
#      - django_react_starter_api
#    ports:
#      - 5432:5432
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data

networks:
  django_react_starter_api:
    driver: bridge
