name: Deploy to production

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  qa_backend:
    uses: ./.github/workflows/qa-backend.yml

  qa_frontend:
    uses: ./.github/workflows/qa-frontend.yml

  deploy:
    needs: [ qa_backend, qa_frontend ]
    name: Deploy app to production using fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy \
          --remote-only \
          --build-arg VITE_ENVIRONMENT=production \
          --build-arg VITE_APP_VERSION=${{ github.ref_name }} \
          --build-arg VITE_SENTRY_DSN=${{ secrets.REACT_SENTRY_DSN }} \
          --env ENVIRONMENT=production \
          --env APP_VERSION=${{ github.ref_name }} \
          --config ./fly/production.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
