name: Deploy to production

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  qa_backend:
    uses: ./.github/workflows/qa-backend.yml

  qa_frontend:
    uses: ./.github/workflows/qa-frontend.yml

  deploy:
    needs: [ qa_backend, qa_frontend ]
    name: Deploy app to staging using fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set APP_VERSION in github environment
        run: |
          echo "APP_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - run: |
          flyctl deploy \
          --remote-only \
          --env APP_VERSION=$APP_VERSION \
          --config ./fly/staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
