name: Rebase Check

on:
  pull_request:
    branches: ['main']

jobs:
  check-rebase-needed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for rebase
        run: |
          git fetch origin main:main
          git checkout ${GITHUB_HEAD_REF}
          if [[ $(git merge-base HEAD main) != $(git rev-parse main) ]]; then
            echo "Branch needs to be rebased onto main!" && exit 1
          else
            echo "Up to date with main."
          fi
