name: Update python dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"  # Every Monday morning

jobs:
  update_deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPENDABOT_PAT }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13" # Cached by github (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#python)
          cache: "pip"
          cache-dependency-path: |
            ./backend/uv.lock

      - name: Install uv
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install uv

      - name: Update dependencies
        run: |
          cd backend
          uv sync --upgrade

      - name: Check for uv.lock changes
        run: |
          git config --global user.name "dependabot[bot]"
          git config --global user.email "49699333+dependabot[bot]@users.noreply.github.com"
          git add ./backend/uv.lock
          if git diff --cached --exit-code --quiet; then
            echo "No changes in uv.lock"
            echo "deps_change=false" >> $GITHUB_ENV
          else
            echo "Changes detected in uv.lock"
            echo "deps_change=true" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: env.deps_change == 'true'
        run: |
          git commit -m "chore: update python dependencies"
          git push -f origin HEAD:deps/update-python-dependencies

      - name: Create Pull Request
        if: env.deps_change == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.DEPENDABOT_PAT }}
          branch: deps/update-python-dependencies
          title: "[Backend] Update python dependencies"
          body: "Update python dependencies"
          assignees: "Jordan-Kowal"
